import type { Metadata } from "next";
import Header from "@/components/Header";
import localFont from "next/font/local";
import { DM_Sans, Inter, Outfit, Lexend } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";



const DMSans = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Mofadj Consult",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DMSans.className} antialiased`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
